# Start up tasks to make things easier:
tasks:
  - name: Terminal 1
    init: python3 -m http.server 8000
  - name: Terminal 2
    before: git init
    init: |
      open index.html
      open style.css
      open script.js